name: Release Please

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy'
        required: true
        default: 'All'
        type: choice
        options:
          - All
          - API
          - Client

jobs:
  release:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        if: github.event_name != 'workflow_dispatch'
        id: release-please
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch' || fromJSON(steps.release-please.outputs.releases_created)
        with:
          fetch-depth: 0

      - name: Deploy API
        if: (github.event_name == 'workflow_dispatch' && contains(fromJson('["All", "API"]'), github.event.inputs.app)) || (fromJSON(steps.release-please.outputs.releases_created) && contains(fromJSON(steps.release-please.outputs.paths_released), 'api'))
        env:
          GITHUB_TOKEN: '${{ secrets.GH_BOT_TOKEN }}'
        run: |
          gh workflow run deploy-api.yml

      - name: Deploy Client
        if: (github.event_name == 'workflow_dispatch' && contains(fromJson('["All", "Client"]'), github.event.inputs.app)) || (fromJSON(steps.release-please.outputs.releases_created) && contains(fromJSON(steps.release-please.outputs.paths_released), 'client'))
        env:
          GITHUB_TOKEN: '${{ secrets.GH_BOT_TOKEN }}'
        run: |
          gh workflow run deploy-client.yml
